modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]]
modId="reproduction"
version="${file.jarVersion}"
displayName="Reproduction"
credits="Thanks for this example mod goes to Java"
authors="Ivan Shvedkov"
description='''
Reproduction mod by Shveed
'''

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="reproduction.png" #optional
#issueTrackerURL="http://my.issue.tracker/" #optional

[[dependencies.reproduction]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reproduction]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
